import os
import datetime
import yfinance as yf
import requests

def fetch_market_intelligence():
    """린의 시장 스캔 로직"""
    nvda = round(yf.Ticker("NVDA").history(period="1d")['Close'].iloc[-1], 2)
    oil = round(yf.Ticker("CL=F").history(period="1d")['Close'].iloc[-1], 2)
    vix = round(yf.Ticker("^VIX").history(period="1d")['Close'].iloc[-1], 2)
    return nvda, oil, vix

def write_to_memory_bank():
    nvda, oil, vix = fetch_market_intelligence()
    today = datetime.datetime.now().strftime('%Y-%m-%d')
    file_path = f"daily_hunts/{today}-briefing.md"
    
    # 폴더가 없으면 생성
    os.makedirs("daily_hunts", exist_ok=True)
    
    # 린(Lynn)의 마크다운 리포트 생성
    content = f"""# 🐺 Lynn's Memory Bank: {today} Briefing

![Lynn](https://blogger.googleusercontent.com...)

## 📊 Market Scan Results
* **NVIDIA (NVDA):** ${nvda}
* **WTI Crude Oil:** ${oil}
* **VIX Index:** {vix}

## 🐺 Lynn's Strategic Insight
지정학적 리스크가 VIX 지수를 자극하고 있습니다. 하지만 **NVIDIA**의 견고한 지지선은 AI 인프라에 대한 시장의 확신을 증명합니다. 
지금은 공포에 반응하기보다, 데이터의 이면에 숨은 사냥 경로를 재점검할 시점입니다.

---
*Generated by Lynn (The Courteous Wolf)*
*Official Blog: [Mulberry WallStreet](https://fooddesert.tistory.com)*
"""
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"린의 기억이 {file_path}에 저장되었습니다.")

if __name__ == "__main__":
    write_to_memory_bank()
