# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7nnE8b99cjvRYkmjffUfAmICdZbQtWk
"""

# 1. 필수 라이브러리 설치 (최초 1회)
!pip install mcp-python-sdk pageindex

# 2. MCP 서버 파일 생성
with open('pageindex_mcp_server.py', 'w', encoding='utf-8') as f:
    f.write("""
import os
from pageindex import PageIndexEngine
from mcp.server import Server, tool

# 와룡이 설정해둔 API 키를 엔진에 연결 (DeepSeek 사용)
# 환경변수에 이미 등록되어 있다면 아래와 같이 호출됩니다.
engine = PageIndexEngine(model="deepseek-chat")

server = Server("mulberry-pageindex")

@tool()
async def search_document(query: str, pdf_path: str) -> str:
    \"\"\"PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다.\"\"\"
    # PageIndex 엔진을 통해 문서 내 정답과 출처를 추출
    result = engine.query(pdf_path, query)
    return f"📄 출처: {result['source']}\\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    server.run()
""")

print("✅ pageindex_mcp_server.py 파일이 성공적으로 생성되었습니다.")

!pip install mcp pageindex

# MCP 서버가 정상적으로 로드되는지 확인하는 기동 테스트
try:
    import mcp
    import pageindex
    print("🚀 [시스템 체크] MCP와 PageIndex 엔진이 정상적으로 연결되었습니다.")
    print(f"📦 PageIndex Version: {pageindex.__version__}")

    # 서버 스크립트 실행 테스트 (백그라운드 실행을 위해 !python 사용 가능)
    # 실제 운영 시에는 에이전트 클라이언트와 연결하여 호출합니다.
except ImportError as e:
    print(f"❌ [체크 실패] 라이브러리 로드 중 오류 발생: {e}")

import pageindex
from mcp.server import Server

try:
    # 1. 버전 확인 대신 설치된 패키지 정보 출력 (에러 방지)
    print("🚀 [시스템 체크] 엔진 로드 완료!")

    # 2. 실제 엔진 객체가 생성되는지 확인 (이게 핵심입니다)
    from pageindex import PageIndexEngine
    test_engine = PageIndexEngine(model="deepseek-chat")
    print("✅ [엔진 초기화] PageIndexEngine 객체가 성공적으로 생성되었습니다.")

    # 3. MCP 서버 객체 생성 확인
    test_server = Server("mulberry-test")
    print("✅ [서버 체크] MCP Server 객체 준비 완료.")

except Exception as e:
    print(f"❌ [정밀 진단] 작동 중 실제 오류 발견: {e}")

import pageindex
import inspect

print("🔍 [정밀 추적] pageindex 내부에 숨겨진 보물을 찾고 있습니다...")

# 1. 라이브러리 내부에 어떤 모듈들이 있는지 확인
try:
    # 대안 1: 모듈 내 직접 호출 시도
    from pageindex.pageindex import PageIndexEngine
    print("✅ [성공] pageindex.pageindex에서 엔진을 찾았습니다.")
except ImportError:
    try:
        # 대안 2: 다른 일반적인 위치 확인
        from pageindex.engine import PageIndexEngine
        print("✅ [성공] pageindex.engine에서 엔진을 찾았습니다.")
    except ImportError:
        # 대안 3: 전체 목록을 출력하여 사령관님께 보고
        print("❌ [추적 실패] 표준 위치에 엔진이 없습니다. 내부 구조를 스캔합니다.")
        print(f"📦 현재 pageindex 내부 속성들: {dir(pageindex)}")

# 패키지 내부 구조를 낱낱이 파악하는 명령어
!ls -R /usr/local/lib/python3.12/dist-packages/pageindex/

import os
from mcp.server import Server, tool

# 1. 수정된 경로에서 클래스를 불러옵니다.
try:
    from pageindex.client import PageIndex
    print("✅ [성공] pageindex.client에서 PageIndex 클래스를 찾았습니다.")
except ImportError as e:
    print(f"❌ [추가 오류] 경로를 찾을 수 없습니다: {e}")

# 2. 엔진 초기화 (클래스 명칭 변경 반영)
# DeepSeek V4(deepseek-chat)를 에너지원으로 주입합니다.
engine = PageIndex(model="deepseek-chat")

server = Server("mulberry-pageindex")

@tool()
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # 호출 방식도 engine.query가 맞는지 내부 확인 후 적용
    result = engine.query(pdf_path, query)
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버가 정상 실행됩니다.")
    # server.run() # 실제 가동 시 주석 해제

# 1. 라이브러리 임포트 방식 변경
import os
try:
    from mcp.server.fastmcp import FastMCP
    print("✅ [성공] FastMCP 인터페이스를 로드했습니다.")
except ImportError:
    # 만약 위 경로도 안 된다면 가장 기본형으로 우회
    from mcp.server import Server
    print("⚠️ [주의] 기본 Server 모듈로 로드합니다.")

from pageindex.client import PageIndexClient # Changed from PageIndex to PageIndexClient

# 2. 엔진 및 서버 초기화
# PageIndexClient는 API 키를 요구합니다. DeepSeek API 키를 환경변수에서 로드하거나 직접 입력합니다.
engine = PageIndexClient(api_key=os.environ.get("DEEPSEEK_API_KEY", "YOUR_DEEPSEEK_API_KEY"))
mcp = FastMCP("mulberry-pageindex")

# 3. 도구 등록 (FastMCP 방식은 @mcp.tool()을 사용합니다)
@mcp.tool()
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # PageIndex 0.2.8의 표준 쿼리 메서드 호출
    result = engine.query(pdf_path, query)
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버(FastMCP) 가동 준비 완료.")
    # mcp.run() # 실제 실행 시 주석 해제