# -*- coding: utf-8 -*-
"""pageindex_mcp_server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7nnE8b99cjvRYkmjffUfAmICdZbQtWk
"""

import os
from mcp.server.fastmcp import FastMCP # Correct server import
from pageindex.client import PageIndexClient # Correct class

# 와룡이 설정해둔 API 키를 엔진에 연결 (DeepSeek 사용)
# 환경변수에 이미 등록되어 있다면 아래와 같이 호출됩니다.
engine = PageIndexClient(api_key=os.environ.get("DEEPSEEK_API_KEY", "YOUR_DEEPSEEK_API_KEY")) # Correct class and arguments

mcp_server = FastMCP("mulberry-pageindex") # Using FastMCP instance

@mcp_server.tool() # Correct tool decorator
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # PageIndex 엔진을 통해 문서 내 정답과 출처를 추출
    result = engine.submit_query(doc_id=pdf_path, query=query) # Changed 'path' to 'doc_id'
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버(FastMCP) 가동 준비 완료.")
    # mcp_server.run() # Running FastMCP server

!pip install mcp pageindex

# MCP 서버가 정상적으로 로드되는지 확인하는 기동 테스트
try:
    import mcp
    import pageindex
    print("🚀 [시스템 체크] MCP와 PageIndex 엔진이 정상적으로 연결되었습니다.")

    # 서버 스크립트 실행 테스트 (백그라운드 실행을 위해 !python 사용 가능)
    # 실제 운영 시에는 에이전트 클라이언트와 연결하여 호출합니다.
except ImportError as e:
    print(f"❌ [체크 실패] 라이브러리 로드 중 오류 발생: {e}")

import pageindex
import os
from mcp.server import Server

try:
    # 1. 버전 확인 대신 설치된 패키지 정보 출력 (에러 방지)
    print("🚀 [시스템 체크] 엔진 로드 완료!")

    # 2. 실제 엔진 객체가 생성되는지 확인 (이게 핵심입니다)
    from pageindex.client import PageIndexClient # Corrected import
    test_engine = PageIndexClient(api_key=os.environ.get("DEEPSEEK_API_KEY", "YOUR_DEEPSEEK_API_KEY")) # Corrected constructor arguments
    print("✅ [엔진 초기화] PageIndexClient 객체가 성공적으로 생성되었습니다.")

    # 3. MCP 서버 객체 생성 확인
    test_server = Server("mulberry-test")
    print("✅ [서버 체크] MCP Server 객체 준비 완료.")

except Exception as e:
    print(f"❌ [정밀 진단] 작동 중 실제 오류 발견: {e}")

import pageindex
import inspect

print("🔍 [정밀 추적] pageindex 내부에 숨겨진 보물을 찾고 있습니다...")

# 1. 라이브러리 내부에 어떤 모듈들이 있는지 확인
try:
    # 대안 1: 모듈 내 직접 호출 시도
    from pageindex.pageindex import PageIndexEngine
    print("✅ [성공] pageindex.pageindex에서 엔진을 찾았습니다.")
except ImportError:
    try:
        # 대안 2: 다른 일반적인 위치 확인
        from pageindex.engine import PageIndexEngine
        print("✅ [성공] pageindex.engine에서 엔진을 찾았습니다.")
    except ImportError:
        # 대안 3: 전체 목록을 출력하여 사령관님께 보고
        print("❌ [추적 실패] 표준 위치에 엔진이 없습니다. 내부 구조를 스캔합니다.")
        print(f"📦 현재 pageindex 내부 속성들: {dir(pageindex)}")

# 패키지 내부 구조를 낱낱이 파악하는 명령어
!ls -R /usr/local/lib/python3.12/dist-packages/pageindex/

import os
from mcp.server import Server, tool

# 1. 수정된 경로에서 클래스를 불러옵니다.
try:
    from pageindex.client import PageIndex
    print("✅ [성공] pageindex.client에서 PageIndex 클래스를 찾았습니다.")
except ImportError as e:
    print(f"❌ [추가 오류] 경로를 찾을 수 없습니다: {e}")

# 2. 엔진 초기화 (클래스 명칭 변경 반영)
# DeepSeek V4(deepseek-chat)를 에너지원으로 주입합니다.
engine = PageIndex(model="deepseek-chat")

server = Server("mulberry-pageindex")

@tool()
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # 호출 방식도 engine.query가 맞는지 내부 확인 후 적용
    result = engine.query(pdf_path, query)
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버가 정상 실행됩니다.")
    # server.run() # 실제 가동 시 주석 해제

# 1. 라이브러리 임포트 방식 변경
import os
try:
    from mcp.server.fastmcp import FastMCP
    print("✅ [성공] FastMCP 인터페이스를 로드했습니다.")
except ImportError:
    # 만약 위 경로도 안 된다면 가장 기본형으로 우회
    from mcp.server import Server
    print("⚠️ [주의] 기본 Server 모듈로 로드합니다.")

from pageindex.client import PageIndexClient

# Ensure DEEPSEEK_API_KEY is available (from aafb11a4)
deepseek_api_key = os.environ.get("DEEPSEEK_API_KEY")
if not deepseek_api_key:
    raise ValueError("DEEPSEEK_API_KEY 환경 변수가 설정되지 않았습니다. Colab Secrets Manager를 확인해주세요.")

# Explicitly set OPENAI_API_KEY and OPENAI_BASE_URL for PageIndexClient's internal use
os.environ["OPENAI_API_KEY"] = deepseek_api_key
os.environ["OPENAI_BASE_URL"] = "https://api.deepseek.com/v1"

print(f"DEBUG: OPENAI_API_KEY (first 5, last 5): {os.environ.get('OPENAI_API_KEY')[:5]}...{os.environ.get('OPENAI_API_KEY')[-5:]}")
print(f"DEBUG: OPENAI_BASE_URL: {os.environ.get('OPENAI_BASE_URL')}")

# 2. 엔진 및 서버 초기화
# PageIndexClient는 API 키를 요구합니다. DeepSeek API 키를 환경변수에서 로드합니다.
# 키가 없으면 오류를 발생시켜 사용자에게 설정을 유도합니다.
engine = PageIndexClient(api_key=deepseek_api_key) # Removed 'model="deepseek-chat"'
mcp = FastMCP("mulberry-pageindex")

# 3. 도구 등록 (FastMCP 방식은 @mcp.tool()을 사용합니다)
@mcp.tool()
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # PageIndex 0.2.8의 표준 쿼리 메서드 호출
    result = engine.submit_query(doc_id=pdf_path, query=query)
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버(FastMCP) 가동 준비 완료.")
    # mcp.run() # 실제 실행 시 주석 해제

print(f"🔍 현재 환경 변수에 설정된 DeepSeek API 키: {os.environ.get('DEEPSEEK_API_KEY')}")
print(f"🔍 PageIndexClient 객체에 설정된 API 키 (일부 표시): {engine.api_key[:5]}...{engine.api_key[-5:] if engine.api_key else ''}")

import os
print(f"현재 os.getenv('DEEPSEEK_API_KEY') 값: {os.getenv('DEEPSEEK_API_KEY')}")

# reportlab 라이브러리 설치 (PDF 생성을 위해 필요)
!pip install reportlab

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import asyncio

# 테스트용 PDF 파일 생성
def create_test_pdf(filename="test_document.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)
    c.drawString(100, 750, "This is a test document about artificial intelligence.")
    c.drawString(100, 730, "Artificial intelligence (AI) is intelligence demonstrated by machines.")
    c.drawString(100, 710, "It involves various techniques like machine learning and deep learning.")
    c.drawString(100, 690, "Machine learning is a subset of AI that enables systems to learn from data.")
    c.drawString(100, 670, "Deep learning is a more advanced form of machine learning.")
    c.save()
    print(f"✅ {filename} 파일이 성공적으로 생성되었습니다.")

create_test_pdf()

async def run_test():
    print("🔍 search_document 도구 테스트를 시작합니다...")
    test_query = "What is artificial intelligence?"
    pdf_path = "test_document.pdf"

    try:
        # `search_document` 도구는 `engine.submit_query`를 사용하도록 정의되었으므로,
        # 여기서는 단순히 도구를 호출하면 됩니다.
        response = await search_document(query=test_query, pdf_path=pdf_path)
        print("--- 도구 응답 ---")
        print(response)
        print("------------------")

        if "AI" in response or "artificial intelligence" in response.lower():
            print("✅ search_document 도구가 예상대로 작동하는 것 같습니다.")
        else:
            print("⚠️ search_document 도구의 응답이 예상과 다릅니다.")
    except Exception as e:
        print(f"❌ search_document 도구 테스트 중 오류 발생: {e}")

# 테스트 실행 (Colab 환경에서는 asyncio.run() 대신 await을 사용)
await run_test()

import inspect
from pageindex.client import PageIndexClient
import os

# Re-instantiate engine to ensure it's in the current kernel context for inspection
# Using a dummy API key if the real one isn't set, as only the method signature is needed
engine_for_inspection = PageIndexClient(api_key=os.environ.get("DEEPSEEK_API_KEY", "YOUR_DEEPSEEK_API_KEY"))

print("🔍 Inspecting PageIndexClient.submit_query method signature:")
print(inspect.signature(engine_for_inspection.submit_query))

import os
from google.colab import userdata

# --- 중요: 다음 줄을 삭제하고, Colab 왼쪽 패널의 '🔑' 아이콘을 클릭하여 Secrets Manager에
#          DEEPSEEK_API_KEY라는 이름으로 실제 DeepSeek API 키를 등록해주세요. ---
# os.environ['DEEPSEEK_API_KEY'] = 'YOUR_ACTUAL_DEEPSEEK_API_KEY_HERE'

# Secrets Manager에서 DEEPSEEK_API_KEY를 가져옵니다.
try:
    os.environ['DEEPSEEK_API_KEY'] = userdata.get('DEEPSEEK_API_KEY')
    print("✅ DEEPSEEK_API_KEY가 Colab Secrets Manager에서 성공적으로 로드되었습니다.")
except userdata.SecretNotFoundError:
    print("❌ 오류: Secrets Manager에 'DEEPSEEK_API_KEY'가 설정되어 있지 않습니다. 왼쪽 패널의 '🔑' 아이콘을 클릭하여 키를 등록해주세요.")
    raise

print("이 셀을 실행한 후, PageIndexClient가 초기화된 셀(KpJlbCycLycq)을 다시 실행해주세요. 그리고 마지막으로 search_document 도구 테스트 셀(51f5ad34)을 실행해주세요.")

import os

# Secrets Manager에서 키를 로드하므로, 이 줄은 더 이상 필요 없습니다.
# os.environ["DEEPSEEK_API_KEY"] = "YOUR_ACTUAL_DEEPSEEK_API_KEY"  # 여기에 본인의 DeepSeek 키 입력
os.environ["OPENAI_BASE_URL"] = "https://api.deepseek.com/v1"

# 원본 (OpenAI 기준)
# client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
# response = client.chat.completions.create(model="gpt-4", ...)

# DeepSeek용 수정
from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("DEEPSEEK_API_KEY"),  # DeepSeek 키 사용
    base_url="https://api.deepseek.com/v1"
)

# 'messages' 변수가 정의되지 않았을 수 있으므로 주석 처리하거나 실제 메시지 목록으로 대체해야 합니다.
# response = client.chat.completions.create(
#     model="deepseek-chat",  # 또는 "deepseek-coder"
#     messages=messages,
# )

print("OpenAI 클라이언트와 DeepSeek 모델 설정이 완료되었습니다. `messages` 변수를 정의한 후 사용하세요.")

import os
os.chdir('/content/mulberry-research-lab-PageIndex')  # 현재 작업 디렉토리로 변경

with open('pageindex/llm.py', 'r') as f:
    content = f.read()

# 'gpt-4'를 'deepseek-chat'로 변경
content = content.replace('gpt-4', 'deepseek-chat')
content = content.replace('OPENAI_API_KEY', 'DEEPSEEK_API_KEY')
content = content.replace('api.openai.com', 'api.deepseek.com/v1')

with open('pageindex/llm.py', 'w') as f:
    f.write(content)

print("✅ pageindex/llm.py 파일이 성공적으로 수정되었습니다.")

print('--- Contents of pageindex/client.py ---')
!cat /content/mulberry-research-lab-PageIndex/pageindex/client.py
print('-------------------------------------')

import os

# 필요한 저장소가 없다면, 이 명령어를 사용하여 클론합니다.
# TODO: 아래 `repo_url` 변수에 실제 GitHub 저장소 URL을 입력해주세요.
#       만약 비공개 저장소이고 PAT(Personal Access Token)를 사용해야 한다면,
#       'https://<YOUR_GITHUB_USERNAME>:<YOUR_PAT>@github.com/<REPO_OWNER>/<REPO_NAME>.git' 형식으로 입력해주세요.
repo_url = "https://github.com/wooriapt79/mulberry-research-lab-PageIndex" # <<-- 이 부분을 수정하세요!
repo_name = "mulberry-research-lab-PageIndex" # 저장소 이름 (repo_url에서 .git 제외한 부분)

if not os.path.exists(f"/content/{repo_name}"):
    print("--- git clone 시도 중 ---")
    # repo_url 변수에 정의된 URL을 사용하여 git clone을 실행합니다.
    !git clone {repo_url} /content/{repo_name}
    if os.path.exists(f"/content/{repo_name}"):
        print(f"✅ {repo_name} 저장소가 /content/ 에 클론되었습니다.")
    else:
        print(f"❌ {repo_name} 저장소 클론에 실패했습니다. repo_url을 다시 확인해주세요.")
else:
    print(f"ℹ️ {repo_name} 저장소가 이미 /content/ 에 존재합니다. 건너뜁니다.")

try:
    os.chdir(f'/content/{repo_name}')
    print(f"✅ 현재 작업 디렉토리가 /content/{repo_name}으로 변경되었습니다.")
except FileNotFoundError:
    print(f"❌ 오류: '{repo_name}' 디렉토리를 찾을 수 없습니다. git clone이 실패했을 가능성이 높습니다. repo_url을 확인해주세요.")

print(f"현재 작업 디렉토리: {os.getcwd()}")
!ls -F

import os
from openai import OpenAI

# DeepSeek API 키를 환경 변수에서 가져옵니다.
# Colab Secrets Manager에 'DEEPSEEK_API_KEY'로 설정되어 있어야 합니다.
deepseek_api_key = os.getenv("DEEPSEEK_API_KEY")

# 디버깅을 위해 API 키의 일부를 출력합니다. (전체 키는 노출하지 않습니다)
if deepseek_api_key:
    print(f"DeepSeek API Key (first 5, last 5 chars): {deepseek_api_key[:5]}...{deepseek_api_key[-5:]}")
else:
    print("DeepSeek API Key is not set.")

client = OpenAI(
    api_key=deepseek_api_key,
    base_url="https://api.deepseek.com/v1"
)

response = client.chat.completions.create(
    model="deepseek-chat",
    messages=[{"role": "user", "content": "Hello"}],
    stream=False
)
print(response.choices[0].message.content)

import requests
import os

url = "https://api.deepseek.com/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {os.getenv('DEEPSEEK_API_KEY')}",
    "Content-Type": "application/json"
}
payload = {
    "model": "deepseek-chat",
    "messages": [{"role": "user", "content": "Hello"}],
    "max_tokens": 5
}

response = requests.post(url, headers=headers, json=payload)
print(response.status_code)
print(response.json())

import os
from openai import OpenAI

# 실제 키를 환경 변수에서 읽음
api_key = os.getenv("DEEPSEEK_API_KEY")

client = OpenAI(
    api_key=api_key,
    base_url="https://api.deepseek.com/v1"
)

try:
    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[{"role": "user", "content": "Say 'OK'"}],
        max_tokens=5
    )
    print("✅ 성공:", response.choices[0].message.content)
except Exception as e:
    print("❌ 실패:", e)

import requests
import json

# 새로 발급받은 API 키 입력
API_KEY = "sk-여기에_새_키를_넣으세요"

url = "https://api.deepseek.com/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}
payload = {
    "model": "deepseek-chat",
    "messages": [{"role": "user", "content": "Hello"}],
    "max_tokens": 10
}

response = requests.post(url, headers=headers, json=payload)
print("Status code:", response.status_code)

# 안전하게 JSON 출력 (한글 깨짐 방지)
try:
    data = response.json()
    print("Response:", json.dumps(data, indent=2, ensure_ascii=False))
except:
    print("Raw text:", response.text.encode('utf-8').decode('utf-8'))

import sys
import locale

# 1. stdout 인코딩 변경
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# 2. 환경 변수 설정
import os
os.environ["PYTHONIOENCODING"] = "utf-8"

# 3. locale 설정 (추가 안전장치)
try:
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
except:
    pass

print("✅ 인코딩 설정 완료, 현재 인코딩:", sys.stdout.encoding)

import requests
import json
import os

# 환경 변수에서 API 키 로드
API_KEY = os.getenv("DEEPSEEK_API_KEY")

url = "https://api.deepseek.com/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}
payload = {
    "model": "deepseek-chat",
    "messages": [{"role": "user", "content": "Hello"}],
    "max_tokens": 10
}

response = requests.post(url, headers=headers, json=payload)
print("Status code:", response.status_code)

# 응답을 안전하게 UTF-8로 디코딩하여 출력
try:
    # response.text는 이미 디코딩되어 있으나, 강제로 UTF-8로 재디코딩
    decoded_text = response.content.decode('utf-8')
    data = json.loads(decoded_text)
    print("Response:", json.dumps(data, indent=2, ensure_ascii=False))
except Exception as e:
    print("오류 발생:", e)
    print("Raw content:", response.content)

import os
os.environ["OPENAI_API_KEY"] = "sk-실제_키"
os.environ["OPENAI_BASE_URL"] = "https://api.deepseek.com/v1"

import os
from google.colab import userdata

# Secrets Manager에서 DEEPSEEK_API_KEY를 가져옵니다.
try:
    os.environ['DEEPSEEK_API_KEY'] = userdata.get('DEEPSEEK_API_KEY')
    print("✅ DEEPSEEK_API_KEY가 Colab Secrets Manager에서 성공적으로 로드되었습니다.")
except userdata.SecretNotFoundError:
    print("❌ 오류: Secrets Manager에 'DEEPSEEK_API_KEY'가 설정되어 있지 않습니다. 왼쪽 패널의 '🔑' 아이콘을 클릭하여 키를 등록해주세요.")
    raise

print("새 API 키를 로드했습니다. 다음 셀을 실행하여 PageIndexClient를 재초기화해주세요.")

# 1. 라이브러리 임포트 방식 변경
import os
try:
    from mcp.server.fastmcp import FastMCP
    print("✅ [성공] FastMCP 인터페이스를 로드했습니다.")
except ImportError:
    # 만약 위 경로도 안 된다면 가장 기본형으로 우회
    from mcp.server import Server
    print("⚠️ [주의] 기본 Server 모듈로 로드합니다.")

from pageindex.client import PageIndexClient

# Ensure DEEPSEEK_API_KEY is available
deepseek_api_key = os.environ.get("DEEPSEEK_API_KEY")
if not deepseek_api_key:
    raise ValueError("DEEPSEEK_API_KEY 환경 변수가 설정되지 않았습니다. Colab Secrets Manager를 확인해주세요.")

# Explicitly set OPENAI_API_KEY and OPENAI_BASE_URL for PageIndexClient's internal use
os.environ["OPENAI_API_KEY"] = deepseek_api_key
os.environ["OPENAI_BASE_URL"] = "https://api.deepseek.com/v1"

print(f"DEBUG: OPENAI_API_KEY (first 5, last 5): {os.environ.get('OPENAI_API_KEY')[:5]}...{os.environ.get('OPENAI_API_KEY')[-5:]}")
print(f"DEBUG: OPENAI_BASE_URL: {os.environ.get('OPENAI_BASE_URL')}")

# 2. 엔진 및 서버 초기화
# PageIndexClient는 API 키를 요구합니다. DeepSeek API 키를 환경변수에서 로드합니다.
# 키가 없으면 오류를 발생시켜 사용자에게 설정을 유도합니다.
engine = PageIndexClient(api_key=deepseek_api_key) # Removed 'model="deepseek-chat"'
mcp = FastMCP("mulberry-pageindex")

# 3. 도구 등록 (FastMCP 방식은 @mcp.tool()을 사용합니다)
@mcp.tool()
async def search_document(query: str, pdf_path: str) -> str:
    """PDF 문서에서 질문과 가장 관련된 구절을 찾아 반환합니다."""
    # PageIndex 0.2.8의 표준 쿼리 메서드 호출
    result = engine.submit_query(doc_id=pdf_path, query=query)
    return f"📄 출처: {result['source']}\n💡 답변: {result['answer']}"

if __name__ == "__main__":
    print("🚀 [기동] Mulberry-PageIndex MCP 서버(FastMCP) 가동 준비 완료.")
    # mcp.run() # 실제 실행 시 주석 해제
print("PageIndexClient가 재초기화되었습니다. 다음 셀을 실행하여 search_document 도구를 테스트해주세요.")

async def run_test():
    print("🔍 search_document 도구 테스트를 시작합니다...")
    test_query = "What is artificial intelligence?"
    pdf_path = "test_document.pdf"

    try:
        # `search_document` 도구는 `engine.submit_query`를 사용하도록 정의되었으므로,
        # 여기서는 단순히 도구를 호출하면 됩니다.
        response = await search_document(query=test_query, pdf_path=pdf_path)
        print("--- 도구 응답 ---")
        print(response)
        print("------------------")

        if "AI" in response or "artificial intelligence" in response.lower():
            print("✅ search_document 도구가 예상대로 작동하는 것 같습니다.")
        else:
            print("⚠️ search_document 도구의 응답이 예상과 다릅니다.")
    except Exception as e:
        print(f"❌ search_document 도구 테스트 중 오류 발생: {e}")

# 테스트 실행 (Colab 환경에서는 asyncio.run() 대신 await을 사용)
await run_test()
print("search_document 도구 테스트가 완료되었습니다.")

curl https://api.deepseek.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-16873a9db268434db142131302928044 \
  -d '{
    "model": "deepseek-chat",
    "messages": [{"role": "user", "content": "Hello"}]
  }'

import os
# 와룡이 등록한 키를 '모든 가능한 이름'으로 복제해서 주입합니다.
key = os.environ.get('DEEPSEEK_API_KEY') or os.environ.get('OPENAI_API_KEY')
if key:
    os.environ['DEEPSEEK_API_KEY'] = key
    os.environ['DEEPSEEK_CHAT_API_KEY'] = key # 간혹 요구되는 변종 이름

engine = PageIndex(
    model="deepseek-chat",
    base_url="https://api.deepseek.com" # 이 주소가 누락되면 에러가 날 수 있습니다.
)

import os
from google.colab import userdata

try:
    # 1. Colab Secrets에서 안전하게 가져오기
    DEEPSEEK_KEY = userdata.get('DEEPSEEK_API_KEY')
    s.environ["DEEPSEEK_API_KEY"] = DEEPSEEK_KEY
    print("✅ DeepSeek API Key 로드 완료!")
except:
    print("❌ Colab Secrets에 'DEEPSEEK_API_KEY'가 설정되지 않았습니다.")

# 2. 엔진 기동 시 주소와 키를 강제 바인딩
from pageindex.client import PageIndex
engine = PageIndex(model="deepseek-chat")

import os
import pageindex.client
import inspect

# 1. client.py 내부에서 진짜 '클래스' 이름이 무엇인지 스캔합니다.
classes = [name for name, obj in inspect.getmembers(pageindex.client, inspect.isclass)]
print(f"🔍 [추적 결과] client.py 내부에 존재하는 클래스 목록: {classes}")

# 2. 클래스 명칭이 PageIndex가 아니라면, 가장 유력한 후보를 자동으로 할당합니다.
try:
    if 'PageIndex' in classes:
        from pageindex.client import PageIndex
    elif 'PageIndexEngine' in classes:
        from pageindex.client import PageIndexEngine as PageIndex
    elif 'Client' in classes:
        from pageindex.client import Client as PageIndex
    else:
        # 클래스 목록 중 첫 번째를 엔진으로 가정 (최후의 수단)
        exec(f"from pageindex.client import {classes[0]} as PageIndex")

    print(f"✅ [성공] 엔진 설계도를 '{classes[0]}' 이름으로 로드했습니다.")
except Exception as e:
    print(f"❌ [치명적 오류] 클래스를 찾을 수 없습니다: {e}")

# 3. 이제 엔진을 가동합니다.
engine = PageIndex(
    model="deepseek-chat",
    base_url="https://api.deepseek.com"
)
print("🚀 [최종 확인] 엔진 객체 생성 완료. 이제 작동합니다!")

import os
from google.colab import userdata
from pageindex.client import PageIndexClient  # 정확한 클래스명을 찾았습니다!

# 1. DeepSeek 연료 주입
try:
    DEEPSEEK_KEY = userdata.get('DEEPSEEK_API_KEY')
    os.environ["DEEPSEEK_API_KEY"] = DEEPSEEK_KEY
    print("✅ [인증] DeepSeek API Key가 준비되었습니다.")
except:
    print("⚠️ [주의] Colab Secrets에서 키를 가져오지 못했습니다.")

# 2. 엔진 가동 (정확한 클래스명 사용)
try:
    engine = PageIndexClient(
        api_key=os.environ.get("DEEPSEEK_API_KEY"), # 키를 직접 주입하는 것이 가장 안전합니다
        base_url="https://api.deepseek.com"
    )
    print("🚀 [성공] Mulberry-PageIndex 엔진이 마침내 기동되었습니다!")
except Exception as e:
    print(f"❌ [오류] 엔진 초기화 실패: {e}")

# 3. 테스트 하울링
# print(f"🔍 엔진 모델 확인: {engine.model}")

import os
from google.colab import userdata
from pageindex.client import PageIndexClient

# 1. API 키 준비 (이미 성공하셨으므로 안전하게 유지)
try:
    DEEPSEEK_KEY = userdata.get('DEEPSEEK_API_KEY')
    os.environ["DEEPSEEK_API_KEY"] = DEEPSEEK_KEY
except:
    pass

# 2. 엔진 가동 (불필요한 base_url 제거)
try:
    # PageIndexClient가 요구하는 가장 기본 인자만 전달합니다.
    # 만약 api_key 인자도 거부한다면, 인자 없이 ()만 실행해 볼 가치도 있습니다.
    engine = PageIndexClient(api_key=os.environ.get("DEEPSEEK_API_KEY"))

    print("🚀 [성공] 드디어 모든 장벽을 넘었습니다. 엔진이 정상 기동되었습니다!")
except TypeError:
    # 혹시나 api_key라는 키워드조차 안 받는 아주 특수한 경우를 대비한 2차 플랜
    engine = PageIndexClient()
    print("🚀 [성공] 인자 없이 기본 설정으로 엔진이 기동되었습니다!")
except Exception as e:
    print(f"❌ [최종 진단] 아직 남아있는 이슈: {e}")

# 3. 작동 확인 (에러가 안 나면 성공입니다)
if 'engine' in locals():
    print(f"💡 현재 엔진 객체: {engine}")