import os
import datetime
import yfinance as yf
import requests

def get_mission_topic():
    """지령서(request.txt)를 읽어 주제를 결정하는 로직"""
    try:
        if not os.path.exists("request.txt"):
            return "Daily Market Scan & Geopolitical Risk Analysis"
            
        with open("request.txt", "r", encoding="utf-8") as f:
            lines = f.readlines()
            for line in lines:
                if "✅ MISSION_TOPIC :" in line:
                    # 콜론(:) 뒤의 내용을 가져오고 대괄호와 공백 제거
                    topic = line.split(":", 1)[1].strip().replace("[", "").replace("]", "")
                    if topic and "여기에" not in topic:
                        return topic
    except Exception as e:
        print(f"Error reading request.txt: {e}")
    return "Daily Market Scan & Geopolitical Risk Analysis"

def fetch_intelligence():
    """시장 지표 수집"""
    nvda = round(yf.Ticker("NVDA").history(period="1d")['Close'].iloc[-1], 2)
    oil = round(yf.Ticker("CL=F").history(period="1d")['Close'].iloc[-1], 2)
    vix = round(yf.Ticker("^VIX").history(period="1d")['Close'].iloc[-1], 2)
    return nvda, oil, vix

def write_memory():
    topic = get_mission_topic()
    nvda, oil, vix = fetch_intelligence()
    today = datetime.datetime.now().strftime('%Y-%m-%d')
    file_path = f"daily_hunts/{today}-briefing.md"
    
    os.makedirs("daily_hunts", exist_ok=True)
    
    content = f"""# 🐺 Lynn's Memory Bank: {today} Briefing
    
## 🎯 Today's Mission: {topic}

## 📊 Market Scan Results
* **NVIDIA (NVDA):** ${nvda}
* **WTI Crude Oil:** ${oil}
* **VIX Index:** {vix}

## 🐺 Lynn's Strategic Insight
지령주제 [{topic}]에 기반한 분석 결과, 현재 시장의 변동성은 기회와 위협의 교차점에 있습니다. 
데이터가 가리키는 사냥 경로를 추적하여 포트폴리오의 방어막을 재정비하십시오.

---
*Generated by Lynn (The Courteous Wolf)*
*Official Blog: [Mulberry WallStreet](https://fooddesert.tistory.com)*
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    write_memory()
